name: 'Terraform Plan'
run-name: Terraform Deploy by '@${{ github.actor }}'

on:
  workflow_call:
    inputs:
      env:
        type: string
        description: Github env to pull vars and secrets from

permissions:
  id-token: write   # This is required for requesting the JWT through OIDC
  contents: read    # This is required for actions/checkout

jobs:
  terraform-plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    env: 
      name: dev_plan

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Normalize Line Endings
        run: |
          sudo apt-get install -y dos2unix
          find . -type f -print0 | xargs -0 dos2unix --quiet --keepdate

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Terraform Init
        working-directory: 'terraform_labs'
        run: terraform init

      - name: Create artifact
        run: echo "This is my artifact" > tfmyplan

      - name: Terraform Plan and save to tfmyplan
        working-directory: 'terraform_labs'
        run: terraform plan -out tfmyplan

      - name: Upload tfmyplan artifact
        uses: actions/upload-artifact@master
        with:
          name: tfmyplan
          path: tfmyplan