name: 'Terraform Apply'
run-name: Terraform Deploy by '@${{ github.actor }}'

on:
  workflow_call:
    inputs:
      env:
        type: string
        description: Environment for folder structure
      environment:
        type: string
        description: Github env to pull vars and secrets from
      project:
        type: string
        description: The terraform project

permissions:
  id-token: write   # This is required for requesting the JWT through OIDC
  contents: read    # This is required for actions/checkout

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: 
      name: dev_deploy

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Normalize Line Endings
        run: |
          sudo apt-get install -y dos2unix
          find . -type f -print0 | xargs -0 dos2unix --quiet --keepdate

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform init
        run: terraform init
        working-directory: 'terraform_labs'

      - name: Download tfmyplan artifact
        uses: actions/download-artifact@master
        with:
          name: tfmyplan
          path: tfmyplan

      - name: Terraform apply
        working-directory: 'terraform_labs'
        run: terraform apply tfmyplan --auto-approve
        