name: 'Terraform Destroy'
run-name: Terraform Destroy by '@${{ github.actor }}'

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  terraform-destroy:
    if: github.event.pull_request.merged == true  && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['dev_plan', 'dev_deploy']
    environment: 
      name: ${{ matrix.environment }}

    steps: 
      - name: Terraform Destroy
        working-directory: 'terraform_labs'
        run: terraform destroy -auto-approve