name: 'Terraform Plan'

on:
    pull_request:
      paths-ignore:
        - '**.md'

env:
    TF_ENV: 'default'

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: 'terraform_labs'
        run: terraform init

      - name: Terraform Plan
        working-directory: 'terraform_labs'
        run: terraform plan